version: '2'
services:
  web:
    build: .
    image: "angularapp-express-run"
    container_name: "angularapp-express-run"
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "development"
      PORT: 3000